app:
    resource: '@AppBundle/Controller/'
    type: annotation

rest_controllers:
    type: rest
    prefix: /v1
    resource: "@AppBundle/Controller/Rest/"

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
